/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'rune-dark': '#080818',
        'rune-bg': '#0e0e24',
        'rune-card': '#1a1a3e',
        'rune-card-hover': '#252550',
        'rune-gold': '#d4a44c',
        'rune-red': '#ef4444',
        'rune-blue': '#3b82f6',
        'rune-purple': '#a855f7',
        'rune-green': '#22c55e',
        'rune-rare': '#34d399',
        'rune-epic': '#fbbf24',
        'rune-orange': '#f97316',
        'rune-cyan': '#06b6d4',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'card-play': 'cardPlay 0.5s ease-out forwards',
        'shake': 'shake 0.5s ease-in-out',
        'shake-hard': 'shakeHard 0.6s ease-in-out',
        'float': 'float 3s ease-in-out infinite',
        'float-slow': 'float 5s ease-in-out infinite',
        'glow-red': 'glowRed 2s ease-in-out infinite alternate',
        'glow-blue': 'glowBlue 2s ease-in-out infinite alternate',
        'glow-purple': 'glowPurple 2s ease-in-out infinite alternate',
        'glow-gold': 'glowGold 2s ease-in-out infinite alternate',
        'glow-rare': 'glowRare 2s ease-in-out infinite alternate',
        'glow-epic': 'glowEpic 2s ease-in-out infinite alternate',
        'enemy-intent': 'intentBounce 1.2s ease-in-out infinite',
        'damage-flash': 'damageFlash 0.4s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-slow': 'fadeIn 1s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'slide-left': 'slideLeft 0.4s ease-out',
        'slide-right': 'slideRight 0.4s ease-out',
        'enemy-hit': 'enemyHit 0.5s ease-out',
        'float-up': 'floatUp 1s ease-out forwards',
        'float-up-green': 'floatUpGreen 1s ease-out forwards',
        'float-up-blue': 'floatUpBlue 1s ease-out forwards',
        'float-up-purple': 'floatUpPurple 1s ease-out forwards',
        'float-up-gold': 'floatUpGold 1s ease-out forwards',
        'card-play-anim': 'cardPlay 0.5s ease-out forwards',
        'shimmer': 'shimmer 2.5s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'spin-reverse': 'spin 6s linear infinite reverse',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'border-epic': 'borderEpic 3s ease-in-out infinite',
        'rune-rotate': 'runeRotate 20s linear infinite',
        'rune-rotate-reverse': 'runeRotate 15s linear infinite reverse',
        'rune-pulse': 'runePulse 4s ease-in-out infinite',
        'title-glow': 'titleGlow 3s ease-in-out infinite',
        'card-draw': 'cardDraw 0.4s ease-out forwards',
        'card-discard': 'cardDiscard 0.3s ease-in forwards',
        'turn-banner': 'turnBanner 2s ease-out forwards',
        'death-fade': 'deathFade 1s ease-out forwards',
        'confetti': 'confetti 3s ease-out forwards',
        'energy-gain': 'energyGain 0.5s ease-out',
        'screen-fade-in': 'screenFadeIn 0.5s ease-out',
        'screen-fade-out': 'screenFadeOut 0.3s ease-in forwards',
        'bounce-in': 'bounceIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'particle-float': 'particleFloat 6s ease-in-out infinite',
        'magic-circle': 'magicCircle 4s linear infinite',
        'attack-slash': 'attackSlash 0.3s ease-out forwards',
        'shield-block': 'shieldBlock 0.4s ease-out forwards',
        'heal-pulse': 'healPulse 0.6s ease-out forwards',
        'fire-burst': 'fireBurst 0.5s ease-out forwards',
        'ice-shatter': 'iceShatter 0.4s ease-out forwards',
        'lightning-strike': 'lightningStrike 0.2s ease-out forwards',
        'poison-drip': 'poisonDrip 0.8s ease-out forwards',
        'hit-spark': 'hitSpark 0.3s ease-out forwards',
        'critical-flash': 'criticalFlash 0.4s ease-out forwards',
        'buff-glow': 'buffGlow 0.8s ease-out forwards',
        'debuff-pulse': 'debuffPulse 0.6s ease-out forwards',
        'enemy-enter': 'enemyEnter 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'path-flow': 'pathFlow 3s linear infinite',
        'node-pulse': 'nodePulse 2s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'text-glow': 'textGlow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        cardPlay: {
          '0%': { transform: 'translateY(0) scale(1) rotate(0deg)', opacity: '1' },
          '30%': { transform: 'translateY(-30px) scale(1.1) rotate(-2deg)', opacity: '0.9' },
          '100%': { transform: 'translateY(-120px) scale(0.5) rotate(5deg)', opacity: '0' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' },
        },
        shakeHard: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-8px, -4px)' },
          '20%': { transform: 'translate(8px, 2px)' },
          '30%': { transform: 'translate(-6px, 4px)' },
          '40%': { transform: 'translate(6px, -2px)' },
          '50%': { transform: 'translate(-4px, 2px)' },
          '60%': { transform: 'translate(4px, -4px)' },
          '70%': { transform: 'translate(-2px, 4px)' },
          '80%': { transform: 'translate(2px, -2px)' },
          '90%': { transform: 'translate(-1px, 1px)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glowRed: {
          '0%': { boxShadow: '0 0 5px #ef4444, 0 0 10px rgba(239,68,68,0.3)' },
          '100%': { boxShadow: '0 0 15px #ef4444, 0 0 30px rgba(239,68,68,0.5), 0 0 45px rgba(239,68,68,0.2)' },
        },
        glowBlue: {
          '0%': { boxShadow: '0 0 5px #3b82f6, 0 0 10px rgba(59,130,246,0.3)' },
          '100%': { boxShadow: '0 0 15px #3b82f6, 0 0 30px rgba(59,130,246,0.5), 0 0 45px rgba(59,130,246,0.2)' },
        },
        glowPurple: {
          '0%': { boxShadow: '0 0 5px #a855f7, 0 0 10px rgba(168,85,247,0.3)' },
          '100%': { boxShadow: '0 0 15px #a855f7, 0 0 30px rgba(168,85,247,0.5), 0 0 45px rgba(168,85,247,0.2)' },
        },
        glowGold: {
          '0%': { boxShadow: '0 0 5px #d4a44c, 0 0 10px rgba(212,164,76,0.3)' },
          '100%': { boxShadow: '0 0 15px #d4a44c, 0 0 30px rgba(212,164,76,0.5), 0 0 45px rgba(212,164,76,0.2)' },
        },
        glowRare: {
          '0%': { boxShadow: '0 0 8px #34d399, 0 0 16px rgba(52,211,153,0.3)' },
          '100%': { boxShadow: '0 0 16px #34d399, 0 0 32px rgba(52,211,153,0.5), 0 0 48px rgba(52,211,153,0.2)' },
        },
        glowEpic: {
          '0%': { boxShadow: '0 0 8px #fbbf24, 0 0 16px rgba(251,191,36,0.3)' },
          '100%': { boxShadow: '0 0 20px #fbbf24, 0 0 40px rgba(251,191,36,0.5), 0 0 60px rgba(251,191,36,0.2)' },
        },
        intentBounce: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(-6px) scale(1.1)' },
        },
        damageFlash: {
          '0%': { backgroundColor: 'rgba(239,68,68,0.4)' },
          '100%': { backgroundColor: 'transparent' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        enemyHit: {
          '0%': { transform: 'translateX(0) scale(1)', filter: 'brightness(1)' },
          '15%': { transform: 'translateX(-8px) scale(0.95)', filter: 'brightness(2.5)' },
          '30%': { transform: 'translateX(8px) scale(1.02)', filter: 'brightness(1.8)' },
          '45%': { transform: 'translateX(-5px) scale(0.98)', filter: 'brightness(1.4)' },
          '60%': { transform: 'translateX(5px) scale(1)', filter: 'brightness(1.2)' },
          '75%': { transform: 'translateX(-2px)', filter: 'brightness(1.1)' },
          '100%': { transform: 'translateX(0) scale(1)', filter: 'brightness(1)' },
        },
        floatUp: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(0.8)' },
          '20%': { opacity: '1', transform: 'translateY(-10px) scale(1.3)' },
          '100%': { opacity: '0', transform: 'translateY(-60px) scale(0.6)' },
        },
        floatUpGreen: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(0.8)' },
          '20%': { opacity: '1', transform: 'translateY(-8px) scale(1.2)' },
          '100%': { opacity: '0', transform: 'translateY(-50px) scale(0.6)' },
        },
        floatUpBlue: {
          '0%': { opacity: '1', transform: 'translateY(5px) scale(0.8)' },
          '20%': { opacity: '1', transform: 'translateY(-8px) scale(1.2)' },
          '100%': { opacity: '0', transform: 'translateY(-45px) scale(0.6)' },
        },
        floatUpPurple: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(0.8)' },
          '20%': { opacity: '1', transform: 'translateY(-8px) scale(1.2)' },
          '100%': { opacity: '0', transform: 'translateY(-50px) scale(0.5)' },
        },
        floatUpGold: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(0.8)' },
          '20%': { opacity: '1', transform: 'translateY(-12px) scale(1.4)' },
          '100%': { opacity: '0', transform: 'translateY(-70px) scale(0.5)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(212,164,76,0.4), 0 0 25px rgba(212,164,76,0.15)' },
          '50%': { boxShadow: '0 0 20px rgba(212,164,76,0.7), 0 0 40px rgba(212,164,76,0.35)' },
        },
        borderEpic: {
          '0%, 100%': { borderColor: 'rgba(251,191,36,0.6)', boxShadow: '0 0 12px rgba(251,191,36,0.3), inset 0 0 12px rgba(251,191,36,0.08)' },
          '33%': { borderColor: 'rgba(168,85,247,0.6)', boxShadow: '0 0 12px rgba(168,85,247,0.3), inset 0 0 12px rgba(168,85,247,0.08)' },
          '66%': { borderColor: 'rgba(239,68,68,0.6)', boxShadow: '0 0 12px rgba(239,68,68,0.3), inset 0 0 12px rgba(239,68,68,0.08)' },
        },
        runeRotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        runePulse: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.08)' },
        },
        titleGlow: {
          '0%, 100%': { textShadow: '0 0 15px rgba(168,85,247,0.6), 0 0 30px rgba(168,85,247,0.3)' },
          '50%': { textShadow: '0 0 30px rgba(168,85,247,0.9), 0 0 60px rgba(168,85,247,0.5), 0 0 90px rgba(168,85,247,0.3)' },
        },
        cardDraw: {
          '0%': { transform: 'translateY(60px) scale(0.7) rotate(-5deg)', opacity: '0' },
          '60%': { transform: 'translateY(-5px) scale(1.02) rotate(1deg)', opacity: '1' },
          '100%': { transform: 'translateY(0) scale(1) rotate(0deg)', opacity: '1' },
        },
        cardDiscard: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '1' },
          '100%': { transform: 'translateY(-40px) scale(0.7)', opacity: '0' },
        },
        turnBanner: {
          '0%': { transform: 'translateX(-120%)', opacity: '0' },
          '15%': { transform: 'translateX(0)', opacity: '1' },
          '85%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(120%)', opacity: '0' },
        },
        deathFade: {
          '0%': { transform: 'scale(1)', opacity: '1', filter: 'brightness(1)' },
          '30%': { transform: 'scale(1.15)', opacity: '0.8', filter: 'brightness(2)' },
          '60%': { transform: 'scale(0.9)', opacity: '0.4', filter: 'brightness(0.5)' },
          '100%': { transform: 'scale(0.3) translateY(30px)', opacity: '0', filter: 'brightness(0)' },
        },
        confetti: {
          '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(1080deg)', opacity: '0' },
        },
        energyGain: {
          '0%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.4)', filter: 'brightness(1.5)' },
          '100%': { transform: 'scale(1)', filter: 'brightness(1)' },
        },
        screenFadeIn: {
          '0%': { opacity: '0', transform: 'scale(0.98)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        screenFadeOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(1.02)' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.2)', opacity: '0' },
          '40%': { transform: 'scale(1.1)' },
          '60%': { transform: 'scale(0.95)' },
          '80%': { transform: 'scale(1.02)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        particleFloat: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)', opacity: '0.6' },
          '25%': { transform: 'translateY(-25px) translateX(15px)', opacity: '1' },
          '50%': { transform: 'translateY(-15px) translateX(-15px)', opacity: '0.8' },
          '75%': { transform: 'translateY(-35px) translateX(8px)', opacity: '0.4' },
        },
        magicCircle: {
          '0%': { transform: 'rotate(0deg)', opacity: '0.5' },
          '50%': { opacity: '0.8' },
          '100%': { transform: 'rotate(360deg)', opacity: '0.5' },
        },
        attackSlash: {
          '0%': { transform: 'scale(0) rotate(-45deg)', opacity: '0' },
          '30%': { transform: 'scale(1.2) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'scale(0) rotate(45deg)', opacity: '0' },
        },
        shieldBlock: {
          '0%': { transform: 'scale(0.5)', opacity: '0' },
          '50%': { transform: 'scale(1.3)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '0.8' },
        },
        healPulse: {
          '0%': { transform: 'scale(0.8)', opacity: '0', filter: 'hue-rotate(0deg)' },
          '50%': { transform: 'scale(1.2)', opacity: '1', filter: 'hue-rotate(20deg)' },
          '100%': { transform: 'scale(1.5)', opacity: '0', filter: 'hue-rotate(40deg)' },
        },
        fireBurst: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '30%': { transform: 'scale(1.5)', opacity: '1' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        iceShatter: {
          '0%': { transform: 'scale(1) rotate(0deg)', opacity: '1' },
          '50%': { transform: 'scale(1.2) rotate(10deg)', opacity: '0.8' },
          '100%': { transform: 'scale(0) rotate(-20deg)', opacity: '0' },
        },
        lightningStrike: {
          '0%': { opacity: '0', transform: 'scaleY(0)' },
          '20%': { opacity: '1', transform: 'scaleY(1.2)' },
          '40%': { opacity: '0.8', transform: 'scaleY(0.9)' },
          '100%': { opacity: '0', transform: 'scaleY(1)' },
        },
        poisonDrip: {
          '0%': { transform: 'translateY(-10px) scale(0)', opacity: '0' },
          '30%': { transform: 'translateY(0) scale(1)', opacity: '1' },
          '100%': { transform: 'translateY(20px) scale(0.5)', opacity: '0' },
        },
        hitSpark: {
          '0%': { transform: 'scale(0) rotate(0deg)', opacity: '0' },
          '20%': { transform: 'scale(1.5) rotate(45deg)', opacity: '1' },
          '100%': { transform: 'scale(0) rotate(90deg)', opacity: '0' },
        },
        criticalFlash: {
          '0%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '30%': { transform: 'scale(1.05)', filter: 'brightness(3)' },
          '60%': { transform: 'scale(0.98)', filter: 'brightness(1.5)' },
          '100%': { transform: 'scale(1)', filter: 'brightness(1)' },
        },
        buffGlow: {
          '0%': { boxShadow: '0 0 0 0 rgba(34,197,94,0.4)' },
          '50%': { boxShadow: '0 0 20px 10px rgba(34,197,94,0.2)' },
          '100%': { boxShadow: '0 0 0 0 rgba(34,197,94,0)' },
        },
        debuffPulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(239,68,68,0.4)' },
          '50%': { boxShadow: '0 0 15px 8px rgba(239,68,68,0.2)' },
          '100%': { boxShadow: '0 0 0 0 rgba(239,68,68,0)' },
        },
        enemyEnter: {
          '0%': { transform: 'translateY(30px) scale(0.5)', opacity: '0' },
          '60%': { transform: 'translateY(-5px) scale(1.05)', opacity: '1' },
          '100%': { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        pathFlow: {
          '0%': { strokeDashoffset: '20' },
          '100%': { strokeDashoffset: '0' },
        },
        nodePulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.15)', opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.5' },
          '50%': { opacity: '1' },
        },
        textGlow: {
          '0%': { textShadow: '0 0 5px currentColor' },
          '100%': { textShadow: '0 0 20px currentColor, 0 0 40px currentColor' },
        },
      },
    },
  },
  plugins: [],
};
